server:
  port: 80
  servlet:
    context-path: /
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  typeAliasesPackage: com.ahrtolia.entity
  mapperLocations: classpath:mapper/*.xml
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    #用于告诉Spring Boot应该在何处查找静态资源文件,查找文件时会依赖于配置的先后顺序依次进行
    #static-locations:
      #classpath: /META-INF/resources/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  datasource:
    url: jdbc:mysql://localhost:3306/eb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 20
  jackson:
    #指定日期格式，比如yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    #指定日期格式化时区
    time-zone: GMT+8